### PR TITLE
Adding instructions to install test-server dependencies

### PR DESCRIPTION
**Pull request by yoshuacas**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@yoshuacas thank you for the documentation update, the patch LGTM. I need you to sign our CLA before I can land it: https://cla.strongloop.com/agreements/strongloop/loopback-sdk-android

**Comment by bajtos** [comment]
Could you also reword the commit message to imperative, i.e. "Add instructions to install test-server dependencies"? If you are not familiar with rewriting git history, the commands are `git commit --amend && git push -f`.

**Comment by bajtos** [comment]
@yoshuacas ping, what's the status of this patch?

**Comment by yoshuacas** [comment]
My apologies, I was not following that I had to sign anything, clearly first time I do this.

**Comment by bajtos** [comment]
Landed via 2eef19a6, thank you for the contribution.

**Pull request closed without merging**
