### PR TITLE
Merge from Ageneau (add find and findOne function)

### PR DESCRIPTION
**Pull request by afaucogney**
This is my first PR (no just for this repo), so as I'm not git neither java expert, I just tried to merge the ageneau contribution with the latest master version.

I think you assign the concerned issue as first prio, but I want to try doing this.

Some commit message are not relevant, but I do not know really how to deal with.

So please be indulgent, and advise me and my work to help in my progress.

Related: #57

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hi @afaucogney, thank you for the pull request, I'll try to review it as soon as feasible. Don't worry about the git commit messages, I can fix them myself before landing the patch.

**Comment by vood** [comment]
@bajtos, any chance you can merge this pull request? It is very important feature for us

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@vood @afaucogney @ageneau I took a closer look at the changes proposed here. AFAICT, there are two major things: 1) fixing/reworking the way how parameters are converted in URL query string 2) add `findOne` method

The second part (`findOne`) is pretty easy to understand, it can be landed soon.

However, I am confused about the parameter conversion, do you happen to know why is this part needed to change, i.e. what bug is this change trying to fix?

**Comment by ageneau** [comment]
@bajtos If I remember correctly I encountered several issues with the flattenMap function (See the 4 new unit tests testRestutil* that should fail with the old version of flattenMap). I think with the changes it should behave the same way as the corresponding javascript library.

**Comment by bajtos** [comment]
Thanks @ageneau for chiming in, I think I should have enough information now.

**Comment by bajtos** [comment]
Closing in favour of #88.

**Pull request closed without merging**
