### PR TITLE
Add port independence

### PR DESCRIPTION
**Pull request by loay**
connect to https://github.com/strongloop/loopback-sdk-android/issues/98

### CODE REVIEW

**Comment by loay** [comment]
@gunjpan PTAL

**Comment by bajtos** [comment]
@loay first of all, I want to have final say before landing this patch.

Could you please describe how did you verify your change works? Our CI is not running the tests, I believe I have mentioned that in the past.

See also https://github.com/strongloop/loopback-sdk-android/blob/8853dbc5606a54b19101e9bf61851bdba830394d/src/androidTest/java/com/strongloop/android/loopback/test/AsyncTestCase.java#L25-L27
```java
    // NOTE: "10.0.2.2" is the "localhost" of the Android emulator's
    // host computer.
    public static final String REST_SERVER_URL = "http://10.0.2.2:3000";

```

**Comment by loay** [comment]
Actually, I just realized that we don't need to do the port independence for this module, as it is not needed. I think this PR should be closed. @bajtos  any objection to that?

**Comment by bajtos** [comment]
Agreed.

**Pull request closed without merging**
