### PR TITLE
- Add Change Password to UserRepository

### PR DESCRIPTION
**Pull request by mekuanent**
### Description
changePassword method has been added to the UserRepository class. It will allow developers to change password easily.

### Checklist

- [x] New tests added
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by b-admike** [comment]
@slnode test please

**Comment by mekuanent** [comment]
@b-admike thank you for your feedback. I have added a content in the manual and made a pull request for this method. And I don't think it's a good idea to have validations and strength checks for passwords because the dev may have their own preferences in this regard.

**Comment by b-admike** [comment]
@slnode test please

**Pull request merged**
