### PR TITLE
Support android studio 1.x

### LINKED ISSUE #67: Upgrade build to the latest version of Android Studio and Build Tools
Our build system is based on pre-1.0 versions of Android Studio and Build Tools. We need to upgrade it to the latest version, otherwise it's super difficult for new developers to contribute to the project - see e.g. https://github.com/strongloop/loopback-sdk-android/issues/55#issuecomment-83272412

### PR DESCRIPTION
**Pull request by bajtos**
Upgrade build:

 - Gradle 2.2
 - android gradle build tools 1.1.0
 - android-maven-plugin 1.2

Upgrade other dependencies too, clean up build.gradle as suggested by Android Studio.

Close #67

### CODE REVIEW

**Comment by bajtos** [comment]
@rmg @cgole Can you please upgrade our CI build slave and install "Android Build Tools" revision 21.1.2?

Instructions from our [wiki](https://strongloop.atlassian.net/wiki/display/SL/Android+SDK+Build+Process#AndroidSDKBuildProcess-SettingupAndroidSDK):

```
# list all SDK components:
$ $ANDROID_HOME/tools/android list sdk --all
  1- Android SDK Tools, revision 22.6.2
  2- Documentation for Android SDK, API 19, revision 2
  [etc.]
# update component no 1 and 2 from the list above
$ $ANDROID_HOME/tools/android update sdk -u -n --all -t 1,2
```

**Comment by bajtos** [comment]
Also please install SDK API version 21.

```
5- Android SDK Build-tools, revision 21.1.2
23- SDK Platform Android 5.0.1, API 21, revision 2
```

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@bajtos upgrade complete.

**Comment by bajtos** [comment]
@rmg Thank you :bow:

**Pull request merged**
